dist: trusty
language: bash


services:
  - docker

before_install:
  - sudo mkdir /opt/devoku
  - curl -L https://api.github.com/repos/adaptivdesign/devoku/tarball | sudo tar xz --strip-components=1 -C /opt/devoku
  - export PATH=$PATH:/opt/devoku/bin/

before_script:
  - devoku service postgres up
  - devoku env new
  - devoku env print
  - devoku pg createdb
  - devoku build

script:
  - devoku run bash runtests.bash
